default:
  image: ruby:2.7.4

build-job:
  stage: build
  script:
    - echo "Hello, I'm ANOTHER!"

build-job-other:
  stage: build
  script:
    - echo "Hello, I'm from pipeline manual var $TEST_VAR!"
    
build-job-third:
  stage: build
  script:
    - echo "Hello, I'm from global var $MY_BRANCH!"    
