default:
  image: ruby:2.7.4

build-job:
  stage: build
  script:
    - echo "Hello, I'm VALUE!"

build-job-other:
  stage: build
  script:
    - echo $TEST_VAR!
    
build-job-third:
  stage: build
  script:
    - echo $MY_BRANCH
