default:
  image: ruby:2.7.4
  
# stages:
#   - build
#   - dock
  
variables:
  WEE: $MY_BRANCH
#   TEST_VAR: $TEST_VAR  

build-job:
  stage: build
  script:
    - echo "Hello, I'm VALUE!"
    - echo "$CI_JOB_JWT"
    - echo $CI_JOB_JWT | base64
    
# send:
#   image: alpine/curl
#   stage: build
#   script:
#     - 'curl -X POST "http://host.docker.internal:8080/rest/v1/webhook/artifact/master/1" -H "X-Gitlab-Token: $CC_M2M_TOKEN"'

build-job-1:
  stage: build
  script:
    - echo "Hello, I'm $DEMO_VAR!"

# build-job-2:
#   stage: build
#   script:
#     - echo "Hello, I'm $MY_BRANCH and $WEE!"
    
# dock:
#   image: docker:19.03.13-dind
#   services:
#     - docker:19.03.13-dind
#   stage: dock
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#   script:
#     - docker build -t $DEMO_VAR/$MY_BRANCH .
#     - docker push $DEMO_VAR/$MY_BRANCH
