default:
  image: ruby:2.7.4
  
variables:
  WEE: $MY_BRANCH
#   TEST_VAR: $TEST_VAR  

build-job:
  stage: build
  script:
    - echo "Hello, I'm VALUE!"

build-job-1:
  stage: build
  script:
    - echo "Hello, I'm $DEMO_VAR!"

build-job-2:
  stage: build
  script:
    - echo "Hello, I'm $MY_BRANCH and $WEE!"
