default:
  image: ruby:2.7.4
  
# stages:
#   - build
#   - dock
  
variables:
  WEE: $MY_BRANCH
#   TEST_VAR: $TEST_VAR  

build-job:
  stage: build
  script:
    - echo "Hello, I'm VALUE!"
    - echo "JOB - > $CI_JOB_MANUAL"

build-job-1:
  stage: build
  script:
    - echo "Hello, I'm $DEMO_VAR!"

build-job-2:
  stage: build
  script:
    - echo "Hello, I'm $MY_BRANCH and $WEE!"
    
# dock:
#   image: docker:19.03.13-dind
#   services:
#     - docker:19.03.13-dind
#   stage: dock
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#   script:
#     - docker build -t $DEMO_VAR/$MY_BRANCH .
#     - docker push $DEMO_VAR/$MY_BRANCH
