variables:
  CC_USER: Super_Odmen
  CC_ENV: $CC_ENV

stages:
  - docker-build
  - docker-push
  - cli-step-deploy
  - cli-step-deploy-param

cli-step-deploy:
  image: nginx:latest
  stage: cli-step-deploy
  script:
    - |
      echo 'hello $CC_USER'
      printenv

cli-step-deploy-param:
  image: nginx:latest
  stage: cli-step-deploy-param
  script:
    - |
      echo 'Env: $CC_ENV'

docker-build:
  image: docker:19.03.13-dind
  stage: docker-build
  services:
    - docker:19.03.13-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo '--$CC_ENV--'
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH .


# docker-push:
#   image: docker:19.03.13-dind
#   stage: docker-push
#   services:
#     - docker:19.03.13-dind
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#   script:
#     - docker push  $CI_REGISTRY_IMAGE:$CC_USER
#     - docker push  $CI_REGISTRY_IMAGE:$CC_ENV
#     - echo "$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH " > images.txt
#   artifacts:
#     paths:
#       - images.txt
#   needs:
#     - project: $CI_PROJECT_PATH
#       job: build_vars
#       ref: $CI_COMMIT_REF_NAME
#       artifacts: true  
