variables:
  CC_USER: Super Odmen
  CC_ENV: $CC_ENV

stages:
  - cli-step-deploy
  - cli-step-deploy-param

cli-step-deploy:
  image: nginx:latest
  stage: cli-step-deploy
  script:
    - |
      echo 'hello $CC_USER'
      printenv

cli-step-deploy-param:
  image: nginx:latest
  stage: cli-step-deploy-param
  script:
    - |
      echo 'Env: $CC_ENV'

