pipeline {
    agent {
        kubernetes {
            yamlFile 'vault/pod.yaml'
        }
    }
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Create Terraform infrastructure') {
            steps {
                container('terraform') {
                    withVault(
                        [
                            configuration: [vaultUrl: 'http://cc-vault:8200',  vaultCredentialId: 'vault_token', engineVersion: 2], 
                            vaultSecrets: 
                            [
                                [
                                    path: 'secret/club', engineVersion: 2, secretValues: 
                                     [
                                        [envVar: 'TEST_DATA', vaultKey: 'data']
                                     ]
                                ]
                            ]
                        ]
                  ) {
                      sh "pwd"
                      sh "ls -l"
                      sh "cat vault/config.txt"
                      sh "terraform --version"
                      sh('echo $env.TEST_DATA')  
//                       sh "echo ${TEST_DATA}"
//                       sh "echo $TEST_DATA > vault/data.txt"
//                       sh "cat vault/data.txt"
                    }
                }
            }
        }
    }
}
