pipeline {
    agent {
        kubernetes {
            yamlFile 'vault/pod.yaml'
        }
    }
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Create Terraform infrastructure') {
            steps {
                container('terraform') {
                    withVault(
                        [
                            vaultSecrets: 
                            [
                                [
                                    path: 'secret/club', engineVersion: 2, secretValues: 
                                     [
                                        [envVar: 'TEST_DATA', vaultKey: 'data']
                                     ]
                                ]
                            ]
                        ]
                  ) {
                      sh "pwd"
                      sh "ls -l"
                      sh "cat vault/config.txt"
                      sh "terraform --version"
                      sh('echo $TEST_DATA')  
                    }
                }
            }
        }
    }
}
