pipeline {
    agent {
        kubernetes {
            yamlFile 'folder/folder-inner/pod-folder-inner.yaml'
        }
    }
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Create Terraform infrastructure') {
            steps {
                container('terraform') {
                  sh "pwd"
                  dir("folder-inner"){
                    sh "pwd"
                    sh "ls -l"
                    sh "cat config.txt"
                    sh "terraform --version"
                  }
                }
            }
        }
    }
}
