pipeline {
    agent {
        kubernetes {
            yamlFile 'folder/pod.yaml'
        }
    }
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Create Terraform infrastructure') {
            steps {
                container('terraform') {
                    sh "pwd"
                    sh "ls -l"
                    sh "cat folder/config.txt"
                    sh "terraform --version"
                }
            }
        }
    }
}
